---
- name: Upload de imagem para EVE-NG (compatível com Python antigo)
  hosts: eve
  gather_facts: no
  vars:
    qemu_base_dir: /opt/unetlab/addons/qemu
    dest_filename: "{{ dest_filename | default('hda.qcow2') }}"

  tasks:
    - name: Criar diretório do template (via raw, sem Python remoto)
      raw: mkdir -p "{{ qemu_base_dir }}/{{ template_name }}"

    - name: Enviar arquivo para o EVE-NG (copia via SCP, sem Python remoto)
      copy:
        src: "{{ local_image_path }}"
        dest: "{{ qemu_base_dir }}/{{ template_name }}/{{ dest_filename }}"
        mode: "0644"
        force: yes
